
- name: Add master nodes to created_instances group
  add_host:
    name={{ item.public_ip }}
    groups=created_instances
    instance_name={{ item.cn }}
  with_items: "{{ all_master_nodes }}"

- name: Add app nodes to created_instances group
  add_host:
    name={{ item.public_ip }}
    groups=created_instances
    instance_name={{ item.cn }}
  with_items: "{{ all_app_nodes }}"

- name: Add infra nodes to created_instances group
  add_host:
    name={{ item.public_ip }}
    groups=created_instances
    instance_name={{ item.cn }}
  with_items: "{{ all_infra_nodes }}"
  when: infra_nodes > 0
  